# Generated by Django 4.0.1 on 2022-01-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_productgroup_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgroup',
            old_name='user',
            new_name='updated_by',
        ),
    ]
