# Generated by Django 4.0.1 on 2022-01-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_productgroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
