# Generated by Django 4.0.5 on 2022-06-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_campaign_created_by_campaign_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
