# Generated by Django 4.0.5 on 2022-06-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_campaign_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('campaign', 'name')},
        ),
    ]
